afilnet.user=emna.awini.work@gmail.com
afilnet.password=Emmaawini123!
afilnet.sender=lama
afilnet.api_key=4d6848f8cf52931f1ea63a831c26040c

# Twilio (Functional Primary)
twilio.account_sid=AC0e88db8397c7c2a2177628598e80a7ce
twilio.auth_token=d6153b389200654fbb4794209eeef67c
twilio.from_number=+21629051913

# Vonage (Primary)
vonage.api_key=YOUR_VONAGE_API_KEY
vonage.api_secret=YOUR_VONAGE_API_SECRET

# Stripe Payment (Test Mode)
stripe.secret_key=sk_test_51OqEFRKka2Z1hxrzMjpHCta6mEVIQsGbAy2PyheDqLplOnJWJ2qEjoqAfya5HN4el3fOanswNCqdMetXca7nrvQT00XFbQXfU8

# Google Gemini AI
gemini.api_key=AIzaSyAzBRH5GkydhqaaX9Hgb_23VjqCmyMJWEA
