afilnet.user=emna.awini.work@gmail.com
afilnet.password=Emmaawini123!
afilnet.sender=lama
afilnet.api_key=4d6848f8cf52931f1ea63a831c26040c

# Vonage (Primary)
vonage.api_key=YOUR_VONAGE_API_KEY
vonage.api_secret=YOUR_VONAGE_API_SECRET
